---
apiVersion: v1
kind: Service
metadata:
  name: dvwa-web-service
spec:
  selector:
    app: dvwa-web
    tier: frontend
  type: NodePort
  ports:
    - protocol: TCP
      # Port accessible inside cluster
      port: 8081
      # Port to forward to inside the pod
      targetPort: 80
